version: "3.7"
services:
  srv:
    build: .
    image: qmcgaw/srv
    container_name: srv
    ports:
      - 8000:8000/tcp
    volumes:
      - ./srv:srv:ro
    environment:
      - HTTP_SERVER_ADDRESS=:8000
      - HTTP_SERVER_ROOT_URL=/
      - HTTP_SERVER_LOG_REQUESTS=on
      - HTTP_SERVER_SRV_FILEPATH=./srv
      - METRICS_SERVER_ADDRESS=:9090
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=America/Montreal
    restart: always
